#!/bin/sh

set -e

OUTPUT=thumbnails
SIZE=512x512

function usage {
    echo usage: thumb [-d destination] [-s size] images...
    exit 1
}

[[ $# -eq 0 ]] && usage

# Parse parameters
while getopts d:s: option
do
    case "${option}" in
        d) OUTPUT="$OPTARG" ;;
        s) SIZE="$OPTARG" ;;
        *) usage ;;
    esac
done

# Create destination directory
mkdir -p "$OUTPUT"

# Shift args to start reading files
shift $(($OPTIND - 1))

declare -a MISSING_FILES

# Convert files
for p in "$@"; do
    if [[ -f "$p" ]]; then
        echo Reducing "$p" to "$SIZE"
        convert "$p" -resize "$SIZE" -background "rgba(0, 0, 0, 0)" -gravity center -extent "$SIZE" "$OUTPUT/$(basename ${p%.*}).png"
    else
        # echo Image "$p" not found
        MISSING_FILES+=($p)
    fi
done

if [[ ${#MISSING_FILES[@]} -ne 0 ]]; then
    echo "The following files couldn't not be found:"
    for e in ${MISSING_FILES[@]}; do echo "\t$e"; done
fi
